### ISSUE TITLE
Can't install with current source

### ISSUE THREAD

**Issue by rawmainb** [OpenStackCookbook/vagrant-ceph#1]
Vagrant version: 2.2.7
VirtualBox version: 6.1.4

When install using `master` branch, error:

```
    ...
    cephaio: Setting up ansible (2.9.6-1ppa~xenial) ...
    cephaio: Processing triggers for libc-bin (2.23-0ubuntu3) ...
    cephaio: Cloning into 'ceph-ansible'...
    cephaio: Note: checking out 'v2.2.9'.
    cephaio: 
    cephaio: You are in 'detached HEAD' state. You can look around, make experimental
    cephaio: changes and commit them, and you can discard any commits you make in this
    cephaio: state without impacting any branches by performing another checkout.
    cephaio: 
    cephaio: If you want to create a new branch to retain commits you create, you may
    cephaio: do so (now or later) by using -b with the checkout command again. Example:
    cephaio: 
    cephaio:   git checkout -b <new-branch-name>
    cephaio: HEAD is now at c259ef5... Merge pull request #1588 from ceph/backport-1587
    cephaio: Generating public/private rsa key pair.
    cephaio: Created directory '/root/.ssh'.
    cephaio: Your identification has been saved in /root/.ssh/id_rsa.
    cephaio: Your public key has been saved in /root/.ssh/id_rsa.pub.
    cephaio: The key fingerprint is:
    cephaio: SHA256:FugebMgoFmeEWumEOpu4VFlA/ABKigDu33vTL96d0bI root@cephaio
    cephaio: The key's randomart image is:
    cephaio: +---[RSA 2048]----+
    cephaio: |++==.            |
    cephaio: |O.=o . .         |
    cephaio: |** o= . .        |
    cephaio: |= == =   .       |
    cephaio: |o*o o = S        |
    cephaio: |=o. .o o      .  |
    cephaio: |.. . .. .    o . |
    cephaio: |.     .o o. . =  |
    cephaio: |     .. o.oo E   |
    cephaio: +----[SHA256]-----+
    cephaio: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBU9L7yYrRzFpeRhW/45rxdXQJIBvyL7qF2Trl4ltgrRe/sR4dkTp6ePdrrhEivNHh0vdvZecLbK59DIVkZ6kvdATeCwzgElpF2W4vRuWZtHSR8yoGKCdWu+TMJG1RYiNEO4yjqy8Bbv1F5HT4FJdO51PWbcGdQEYTUzF70Vp7HObrooCGbs+CsFFt00TZM+31IuP2ZZNkeOm6C5dG33sTcL7DWZBHOQrCJvSqGommENioUAFx1BkDRgcj57Du1q+ze9NR59gfVr6dG9L7xSL15mFG+9Jsr1bKMXeTs2b3UNKMYKZND4K2qbImJM9KjZj8gEa/v2zLRD6aVacmYCnD root@cephaio
    cephaio: [DEPRECATION WARNING]: The use of 'static' has been deprecated. Use 
    cephaio: 'import_tasks' for static inclusion, or 'include_tasks' for dynamic inclusion. 
    cephaio: This feature will be removed in version 2.12. Deprecation warnings can be 
    cephaio: disabled by setting deprecation_warnings=False in ansible.cfg.
    cephaio: ERROR! conflicting action statements: command, always_run
    cephaio: 
    cephaio: The error appears to be in '/home/vagrant/ceph-ansible/roles/ceph-common/tasks/facts.yml': line 2, column 3, but may
    cephaio: be elsewhere in the file depending on the exact syntax problem.
    cephaio: 
    cephaio: The offending line appears to be:
    cephaio: 
    cephaio: ---
    cephaio: - name: get ceph version
    cephaio:   ^ here
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
```
